//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarhatnyeHolmy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderService = new HashSet<OrderService>();
        }
    
        public int Order_id { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.TimeSpan TimeCreate { get; set; }
        public int Clients_Client_Id { get; set; }
        public int OrderStatus_Status_id { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public Nullable<int> UseTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderService> OrderService { get; set; }
    }
}
