//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarhatnyeHolmy
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int Order_Service_id { get; set; }
        public int Orders_Order_id { get; set; }
        public int Services_Service_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
